### ISSUE TITLE
FR15. Admin Login

### ISSUE THREAD

**Issue by Kyle-WSU** [WSU-4110/Wayne-State-Blood-Bank#15]
|FR15. Admin Login|
|---|
|**Goal**: Secures user data
**Stakeholders:** Administrators |
| **Description:**  separate the regular users from the administrators of the website, so the regular users will be restricted from using the admin privileges.  |
| **Origin:** Initial brain storm from the group  |
| **Version:** 1.0  |
|**Date:** 9/22/2020
|  **Priority:** HIGH |

**Comment by jacobboesch** [comment]
Admin login uses the same login page as regular login. The system keeps track of which users have admin privilege's and which ones don't. This feature has been completed.
