### ISSUE TITLE
FR19. Adding stars to the users who donated

### ISSUE THREAD

**Issue by Kyle-WSU** [WSU-4110/Wayne-State-Blood-Bank#19]
|FR19. Adding stars to the users who donated|
|---|
|**Goal**: Users will be kept updated about the number of stars they have and make use of it for any incentives.
**Stakeholders:** Administrators |
| **Description:**  Once the user uploads the proof of donation, the admins will review those carefully. If it confirms the donation, the admins will add stars to the user profile.  |
| **Origin:** Initial brain storm from the group  |
| **Version:** 1.0  |
|**Date:** 9/22/2020
|  **Priority:** MEDIUM |

**Comment by jacobboesch** [comment]
The team decided to replace this feature with the view blood requests. 
And the team leader Tia spoke with the professor to confirm that we would be able to replace this feature
with the new feature of view blood requests.
