### ISSUE TITLE
NR6. Consent prior to storing information

### ISSUE THREAD

**Issue by Kyle-WSU** [WSU-4110/Wayne-State-Blood-Bank#25]
|NR6. Consent prior to storing information|
|---|
|**Goal**: To increase the comfortability that users can use the website and request for blood without fear of losing data.
**Stakeholders:** Blood Requesters, Blood Donors |
| **Description:**  When I request for a blood donor, I would be inputting the cell number, email id, blood type etc. This information won't be saved to the system, but would be considered as temporary data and will be only used while sending the email so the user need not worry while they enter the data in the blood request form. |
| **Origin:** Initial brain storm from the group  |
| **Version:** 1.0  |
|**Date:** 9/22/2020
|  **Priority:** HIGH |

**Comment by jacobboesch** [comment]
This requirement could not be complete due to it conflicting with the view requests requirement. Therefore, the data needed to be stored.
