### ISSUE TITLE
FR6.  Upload info for incentives

### ISSUE THREAD

**Issue by Kyle-WSU** [WSU-4110/Wayne-State-Blood-Bank#6]
|FR6.  Upload info for incentives|
|---|
|**Goal**: Upload proof of donation. 
**Stakeholders:** Blood donors |
| **Description:** Description: Users are rewarded with an electronic star for confirmed donations. Once a donation is complete, in their profile page they will submit evidence to the admin team who can then award a star. The number of stars will be visible from the users profile page 
This feature is restricted to verified users only.  |
| **Origin:** Initial brain storm from the group  |
| **Version:** 1.0  |
|**Date:** 9/22/2020
|  **Priority:** LOW |

**Comment by jacobboesch** [comment]
The team decided to replace this feature with the view blood requests feature.
And the team leader Tia spoke with the professor to confirm that we could swap this feature for the view blood requests feature.
